### ISSUE TITLE
Not work with 57.0b5

### ISSUE THREAD

**Issue by prowler86** [MatMoul/quickdial-webext#1]
Thanks for new Fast Dial. But it is not work 57.0b5

**Comment by MatMoul** [comment]
Can you give me more details?
What error do you encounter?

**Comment by prowler86** [comment]
![2017-10-05_23-33-24](https://user-images.githubusercontent.com/1527966/31251140-a73d7650-aa25-11e7-97c3-042bd078887b.png)
can't add links. they are not visible
![2017-10-05_23-34-36](https://user-images.githubusercontent.com/1527966/31251174-c3e0ca64-aa25-11e7-8e59-2df0f6e7d7c2.png)

**Comment by MatMoul** [comment]
Can you try to remove the plugins delete the Quick Dial folder in your bookmark and install it again... 
I Have tested with chinese characters and it work, cyrilic characters need to work... 

If this don't work, try to open the debug console (F12) and send me what the console say...

**Comment by prowler86** [comment]
Thanks. It works now. Awesome addon.

How to make quick dial is a default homepage when I open FF?

**Comment by MatMoul** [comment]
Open an emty tab with quick dial and the settings page of Firefox and click on current page...

**Comment by prowler86** [comment]
I have already made it. But when I open firefox it still open a in-built quick acces page.
![2017-10-06_23-15-07](https://user-images.githubusercontent.com/1527966/31296810-597a374c-aaec-11e7-8805-ccd136856f69.png)
![2017-10-06_23-12-04](https://user-images.githubusercontent.com/1527966/31296811-597cefb4-aaec-11e7-98d4-f84ac2bd4a91.png)
![2017-10-06_23-12-24](https://user-images.githubusercontent.com/1527966/31296812-598a9c5e-aaec-11e7-8877-dd58f2a26acc.png)

**Comment by MatMoul** [comment]
Try to use Show my windows and tabs from list time in When Firefox starts, this work better...
If this don't work, you have an other extention that shortcut my page

**Comment by prowler86** [comment]
Well it works. I have made this
![2017-10-07_18-14-35](https://user-images.githubusercontent.com/1527966/31309229-805eaab0-ab8b-11e7-9b24-b1657cbca322.png)
