### ISSUE TITLE
Clicking a link which is assigned to a non-default container opens two tabs

### ISSUE THREAD

**Issue by scienmind** [MatMoul/quickdial-webext#10]
As the title goes, if a website is assigned to permanently open in a certain container, launching it from Quick Dial results in opening 2 new tabs (1 background) with this website.

Potentially related: https://github.com/MatMoul/quickdial-webext/issues/9

**Comment by scienmind** [comment]
Happens only with http bookmarks which are redirected to https. Otherwise works fine.
Not sure if Quick Dial is the cause, however with FF's default new tab that doesn't happen.

**Comment by MatMoul** [comment]
I will resolve #9 before and see if this is related

**Comment by MatMoul** [comment]
Look at #9 to know why I tagged Unsupported feature (ff57)

**Comment by MatMoul** [comment]
@scienmind Can you test with version 0.1.0 ?

**Comment by scienmind** [comment]
seems fixed to me 👍
