### ISSUE TITLE
Can't click and regular bookmarks won't load

### ISSUE THREAD

**Issue by yolinfl** [MatMoul/quickdial-webext#105]
Since your update and FF62 the Quick Dial doesn't work properly anymore.
I've re-installed the Quick Dial, but after opening QD my tab freezes. Also regular bookmarks from my FF bar won't appear. You see them loading in the tab (swapping ball) but nothing happens. When I de-install QD it works fine. But I want to use QD as I like it.
Anyone else having this issues? Can this be solved?

**Comment by MatMoul** [comment]
Can you check the the issue #104 ?
Is this the same problem (Flash Video Downloader) ?
QD work fine on FF62 and I don't make any update...

**Comment by yolinfl** [comment]
I've read issue 104, but deinstalling FVD didn't work for me. And even worse, now the QD icon in my toolbar is like a blank icon. When I started FF again I did get the message to save the settings, which I did. 
I now have QD installed, FVD deinstalled or even installed, but now with the results I can't use QD at all. FF updated to 62 as well. 
Any other ideas? I miss using it!

**Comment by MatMoul** [comment]
Is this case closed?
If yes, what the solution?
If this case is the same as https://addons.mozilla.org/fr/firefox/addon/quick-dial/reviews/ and is you (yolandal), please, update the comment...

**Comment by MatMoul** [comment]
Thank's...
