### ISSUE TITLE
Address bar not focused when new window opened after setting extension as homepage.

### ISSUE THREAD

**Issue by XedMada** [MatMoul/quickdial-webext#106]
If I set the extension as the firefox homepage it successfully shows when creating a new window, however the cursor focus is on the page instead of the location bar as expected. New tabs focus the location bar, but new windows do not.

With a bit of digging I found [this firefox bug entry](https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1411209) which also reports on the behavior. The strange thing is that the other "quickdial-like" extension I sometimes use does not suffer this issue, always focusing the location bar when a new window is created while it is set as my homepage. I'm wondering if there might be a way around this issue? I queried the other extension's dev, but no response yet.

MacOS 10.13.4 - FF 62.0 - Quick Dial 0.1.13. Behavior persists in clean VM of similar environment with Quick Dial as only installed extension.

**Comment by MatMoul** [comment]
QuickDial don't handle first focus but the default behaviour is to set focus to adressbar...
I've encouter this problem these last days but now it seem work now in FF62.0.2
Can you confirm ?

**Comment by MatMoul** [comment]
Sorry my reply is for new opened tab and not new window...
With new window, I encouter the issue...

**Comment by XedMada** [comment]
Confirming new window still loses addressbar focus in FF 62.0.2.

I now notice that it is actually "losing" the addressbar focus on creation of a new window. i.e. I can see the focus highlight appear on the addressbar for maybe half a second then disappear. If I then [Tab], [Shift]+[Tab], [Shift]+[Tab] the address bar is back in focus. Not certain if this is new behavior in FF 62.0.2 tho, my testing VMs are currently unavailable.

**Comment by MatMoul** [comment]
Switching tag because the issue is on FF and I've not found any solution in API
Wait and see

**Comment by MatMoul** [comment]
Definitely managed and restricted by FF
