### ISSUE TITLE
Feature Request: Open immediately if Firefox starts (initial first tab)

### ISSUE THREAD

**Issue by benboeck** [MatMoul/quickdial-webext#107]
Thank you for the great extension, exactly the simple solution I was looking for!

Feature request:

- Open quick dial immediately on the first initial tab when Firefox starts
  - One way to implement this would be to set quick dial as homepage, if this is possible; homepage can then be set in Firefox settings so that quick dial opens immediately on the first tab if Firefox is started.

Thank you,
kind regards,

Ben

**Comment by Tybee921** [comment]
This is the way QD has always worked.  Set it as the homepage in Firefox and it starts up automatically.  My problem is that the initial start up has stopped working for me on 4 computers.

**Comment by MatMoul** [comment]
Not a feature request but a new comportement of Firefox...
Issue #108 as a best title for this issue

**Comment by MatMoul** [comment]
I close the issue because the issue #108 is almost solved.
If this isn't reply to your question, reopen the issue or a new issue
