### ISSUE TITLE
New Private Window Speed-dial doesn't open

### ISSUE THREAD

**Issue by Acid-Crash** [MatMoul/quickdial-webext#11]
When opening New Private Window and then clicking on the New tab Speed-Dial fails to load.
Only FavIcon (in tab) is changed to Extension one but the actual Speed-Dial window remains blank.
Tested on Latest Nightly Win10x64.
FF privacy settings
Clear history when FF/Nightly closes - cache, cookies.
![pwm](https://user-images.githubusercontent.com/32600318/31491976-d7efa576-af51-11e7-9382-7b19e3bd5520.png)

**Comment by scienmind** [comment]
Sort-of duplicate of #9

**Comment by Acid-Crash** [comment]
Oh sorry didn't see that one. Should I close this one?

**Comment by scienmind** [comment]
Thinking about it, probably leave it open.
While both issues do have the same underlying cause, fixing one of then will not necessarily fix it all.

**Comment by MatMoul** [comment]
@Acid-Crash Leave this issue open, I will work on it this week-end

**Comment by MatMoul** [comment]
Version 0.1.0 published with Private Window support
