### ISSUE TITLE
Lock image not working (Firefox)

### ISSUE THREAD

**Issue by tyfarobinson** [MatMoul/quickdial-webext#119]
**EDIT: Issue has seemingly been resolved by reinstalling Quick Dial. For more details, see my second post.**

I keep having an issue with some but not all of my bookmarks. Only a select few seem to be behaving strangely. I've attached a bunch of images to highlight the issue I'm facing. Four of the websites I bookmark aren't showing the custom images I locked them to use. **None of the images have moved or had their names changed,** and I've recreated the bookmarks several times, but whenever Quick Dial loads after an ended browsing session, these four bookmarks lose their image almost every time and a new image can not be put back in. I can browse to the image, but it won't update properly. The links still works, but I can't fix the broken images. The only way is to delete and then recreate the bookmarks, but the problem happens every time. One time, GameStop's bookmark didn't even load the locked title, though that only happened once and I don't have in image for it.

This is what the bookmarks look like after being made and before being customized and locked.
<img width="375" alt="supporta" src="https://user-images.githubusercontent.com/46060178/50389523-74571c00-06f9-11e9-9331-3855c859b269.PNG">

This is how I customized Wells Fargo's bookmark.
<img width="386" alt="supportb" src="https://user-images.githubusercontent.com/46060178/50389524-74571c00-06f9-11e9-999f-f3b209d341f5.PNG">

This is how I customized PayPal's bookmark.
<img width="389" alt="supportc" src="https://user-images.githubusercontent.com/46060178/50389525-74571c00-06f9-11e9-8698-c3dee0c86172.PNG">

This is how I customized GameStop's bookmark.
<img width="393" alt="supportd" src="https://user-images.githubusercontent.com/46060178/50389526-74571c00-06f9-11e9-8fa0-16b1f2ae5fab.PNG">

This is what the bookmarks look like after being customized and before the bug takes effect.
<img width="313" alt="supporte" src="https://user-images.githubusercontent.com/46060178/50389762-1aa42100-06fc-11e9-91a5-26911b50de83.PNG">

After closing and reopening the browser, this is what the images do. They become animated low-resolution loading icons that seemingly do not go away at all.
<img width="325" alt="supportf" src="https://user-images.githubusercontent.com/46060178/50389527-74571c00-06f9-11e9-9832-35d581188249.PNG">

The broken versions of the bookmarks. They don't display any image or allow me to put a new one in, even if it's entirely different from what it used to be.
<img width="390" alt="supportg" src="https://user-images.githubusercontent.com/46060178/50389528-74efb280-06f9-11e9-9207-7f2b5ed5fc7a.PNG">
<img width="390" alt="supporth" src="https://user-images.githubusercontent.com/46060178/50389529-74efb280-06f9-11e9-8981-6d1665671471.PNG">
<img width="396" alt="supporti" src="https://user-images.githubusercontent.com/46060178/50389530-74efb280-06f9-11e9-91fc-8ad046322864.PNG">

After getting all the previous images, I noticed my brand new bookmark for Pixabay stopped working as well.
<img width="104" alt="supportj" src="https://user-images.githubusercontent.com/46060178/50389531-74efb280-06f9-11e9-9156-702b3444da7d.PNG">

Broken version of Pixabay bookmark.
<img width="390" alt="supportk" src="https://user-images.githubusercontent.com/46060178/50389532-74efb280-06f9-11e9-965e-619e73ec009d.PNG">

I made a new bookmark aside of it to show what it is supposed to be.
<img width="388" alt="supportl" src="https://user-images.githubusercontent.com/46060178/50389533-74efb280-06f9-11e9-8406-f273941bf7a1.PNG">

It broke too.
<img width="209" alt="supportm" src="https://user-images.githubusercontent.com/46060178/50389534-74efb280-06f9-11e9-8d17-c19f23a8ce84.PNG">

**IMPORTANT THINGS TO NOTE:**
- **I'm not using Private Browsing in Firefox, cookies are properly set to not be deleted after browsing.**
- **Firefox is up to date.**
- **Quick Dial is up to date.**
- **On the main page, there are 9 bookmarks and 3 folders, all working fine.**
- **Quick Dial's grid is set to 4 tall and 3 wide.**
- **In Folder A, there are 8 bookmarks and the back button, all working fine.**
- **In Folder B, there are 9 boomarks and the back button, one of the bookmarks is broken, but everything else is fine.**
- **In Folder C, there are 8 bookmarks and the back button, three of the bookmarks are broken, but everything else is fine.**
- **The four broken bookmarks are likely to be the most recent.**

Is there anything I can do to fix this, such as a number I can edit where Quick Dial stores the bookmarks?

**Comment by MatMoul** [comment]
@tyfarobinson Thanks for your return...
I close the issue but if you encounter the same problem reopen this issue
