### ISSUE TITLE
v.0.1.0 regression: Backgroung color flickering when opening subfolders

### ISSUE THREAD

**Issue by scienmind** [MatMoul/quickdial-webext#12]
Steps:
1. Set custom background color
2. Open Quick Dial
3. Open Subfolder

On transition to the subfolder, the background quickly change from defined color to white and back to defined color.

In 0.4.0 the color was not flickering and the transition was visually smooth. Tested side by side.

Curiously, the flicker happens only when "entering" folders, going "back" to parent one is smooth as before.

**Comment by MatMoul** [comment]
Message system has some bad side effects in performance...
I'll try to optimize

**Comment by scienmind** [comment]
Some more info:
1. Open Quick Dial
2. Click on subfolder
 -- flicker -- 
3. Click back (button or ALT+Left)
-- no flicker -- 
 - 3.1. Enter the same folder again using "forward" (toolbar or ALT+Right)
  -- no flicker -- 
 - 3.2. Enter the same folder again by clicking the subfolder again
  -- flicker --

**Comment by MatMoul** [comment]
this is due to the time set by the sendmessage function.
I'll try to find a solution but i'm very limited...

**Comment by scienmind** [comment]
Since "forward" doesn't have the issue, maybe preloading/caching some way can help.

But the proper way would probably be to redraw only the grid on clicks and keep the background constant once Quick Dial is opened.

**Comment by MatMoul** [comment]
I've found a temporary solution comming with the next release, now I try to work on new features

**Comment by MatMoul** [comment]
Try version 0.1.2, normally fixed for color but not for image.

**Comment by scienmind** [comment]
Background color flickering fixed in 0.1.2 
👍

**Comment by scienmind** [comment]
Now only the grid redraw "flickers" (as it began in 0.1.0). While annoying, not as nearly nauseating as the background was...

**Comment by MatMoul** [comment]
For this, I don't have any idea... sendmessage is slow and I need to make with it...
