### ISSUE TITLE
Contextual menu

### ISSUE THREAD

**Issue by Stephdv** [MatMoul/quickdial-webext#13]
Hi
I use firefox on MacOs and since the last release i loosed the capacity to add a bookmark via the contextual menu on right click.
No possibility to add any bookmarks in fact

**Comment by scienmind** [comment]
Can confirm with v.0.1.3:

1. Open Quick Dial
2. Right click -> New -> Bookmark

Now: if the site is entered with `https://` prefix (e.g. `https://www.wikipedia.com/`), it'll work fine.
However, entering just `www.wikipedia.com` without the prefix won't create the bookmark.

**Comment by Stephdv** [comment]
Ok, thank you
But it would be easier to have the feature directly on right click in contextual menu on the webpage...

**Comment by scienmind** [comment]
I think there are two separate bugs here. 
@Stephdv 's original report is probably fixed here: https://github.com/MatMoul/quickdial-webext/commit/325fdc8c838a80670219992a6f4c883f6d819d5f.

And the one I described have something to do with url parsing after [this call](https://github.com/MatMoul/quickdial-webext/blob/master/src/js/dial.js#L389).

**Comment by MatMoul** [comment]
I just added a solution that add http:// if no sheme is provided : https://github.com/MatMoul/quickdial-webext/commit/957f468c59002760a9d0c6acfad6325bcb35ccd8
Reenabled the add to quick dial menu item : https://github.com/MatMoul/quickdial-webext/commit/325fdc8c838a80670219992a6f4c883f6d819d5f
And I have corrected a bug when parsing data : https://github.com/MatMoul/quickdial-webext/commit/245d70a6eb6061069bae669deefb937eaeeb03fd
I'll publish a release in some hours...

**Comment by MatMoul** [comment]
I published the new version 0.1.4.
Reopen the issue if needed

**Comment by Stephdv** [comment]
thank you, it runs fine :)
