### ISSUE TITLE
QuickDial couldn't be verified and was desactivated

### ISSUE THREAD

**Issue by Garro89** [MatMoul/quickdial-webext#134]
As in the headline, FF informed me today that QuickDial couldn't be verified and was desactivated. Now I cannot use it anymore. What should I do?

**Comment by Garro89** [comment]
FF 66.0.3 (64 bity)/win 10

**Comment by holschrei** [comment]
Same here ---> https://github.com/MatMoul/quickdial-webext/issues/133

**Comment by MatMoul** [comment]
It's a Mozilla issue, more info here :
https://twitter.com/firefox/status/1124527050490933248

**Comment by holschrei** [comment]
Thanks a lot
