### ISSUE TITLE
FVD Not Displaying when opening FF

### ISSUE THREAD

**Issue by bWildcard** [MatMoul/quickdial-webext#135]
I know this isn't a new issue and others have had it in the past but when ever I open FireFox all I get now is a Blank White Page instead of what I have the homepage set to as moz-extension://2a4dd34d-e933-417d-801f-c2d95e77706a/newtab.html  I have tried resetting the page using a blank then back to FVD as well as other custom URLs  ive even tried doing multiple customs like google.com|moz-extension://2a4dd34d-e933-417d-801f-c2d95e77706a/newtab.html and the second tab thats supposed to be FVD shows Blank White as well.   Ive tried removing it and reinstalling it and that doesn't seem to work either. 

Anyone have any thoughts?

**Comment by MaximilianKohler** [comment]
Why would you close this without a solution being given...
