### ISSUE TITLE
Design suggestion.

### ISSUE THREAD

**Issue by Acid-Crash** [MatMoul/quickdial-webext#14]
Hi, recently I've been experimenting with FF default Activity Stream (about:newtab).
I find it's design quite fluent so I've tried to replicate some parts for QuickDial.

Here is the result
![qd](https://user-images.githubusercontent.com/32600318/31587538-3be64548-b1ec-11e7-8aa9-fae32492192b.png)

.Grid td > a {border: 0px solid rgb(51, 51, 51) !important;}

.Grid td > a.Bookmark :first-child, .Grid td > a.Folder :first-child, .Grid td > a.Back :first-child {
    border-radius: 6px !important;
    box-shadow: inset 0 0 0 1px rgba(215, 215, 219, 0.3), 0 1px 4px 0 rgba(12, 12, 13, 0.7) !important;
    margin: 5px !important;
    transition: box-shadow 50ms !important;
}

.Grid td > a.Bookmark :first-child:hover, .Grid td > a.Folder :first-child:hover, .Grid td > a.Back :first-child:hover {
    border-radius: 6px !important;
    box-shadow: inset 0 0 0 1px rgba(0, 0, 0, 0.1), 0 0 0 5px #D7D7DB !important;
    transition: box-shadow 150ms !important;
}    

.Grid td > a > div:last-child {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Ubuntu", "Helvetica Neue", sans-serif !important;
    font-size: 12px !important;
    border-top: 0 solid rgb(51, 51, 51) !important;
    white-space: nowrap !important;
    text-overflow: ellipsis !important;
    padding: 2px 13px 0 !important;
} 

Maybe you consider adding some of the parts to make extension more polished.

**Comment by MatMoul** [comment]
Good result...
font, box-shadow, transition will be added in the future but I have other priorities before...
I need to find a solution that is accessible to all. So each settings need to be updated in quick dial settings.

**Comment by Acid-Crash** [comment]
Hi, I've made some minor changes to style (updated my original post)
Noticed some unnecessary shadows on folder tile.

**Comment by Acid-Crash** [comment]
Hi. Just noticed that piece of my styling makes images more stretched (most noticable when placing Circle picture as a tile BG).
Looks like it because of `margin: 5px !important;`
Unfortunately I cant understand why this happens

**Comment by MatMoul** [comment]
@Acid-Crash I use script for resizing the grid and this content... (I work directly on the classname with js)
When your override my css, your margin, border size and box shadow are not handled...

**Comment by MatMoul** [comment]
Follow #36, the stability allow now to add custom css feature but I need to write the code ;)

**Comment by Acid-Crash** [comment]
Happy to hear this. 
If needed here is the CSS I'm currently using. 
I've cheated with overflow:visible !important; to omit additional margins for hover state
Commented-out box shadows are for light wallpapers


.Grid td > a {border: 1px solid rgba(51, 51, 51, 0) !important;overflow:visible !important;}
.Grid td > a.Bookmark :first-child, .Grid td > a.Folder :first-child, .Grid td > a.Back :first-child {
    border-radius: 6px !important;
    box-shadow: inset 0 0 0 1px rgba(215, 215, 219, 0.3), 0 1px 4px 0 rgba(12, 12, 13, 0.4) !important;
    /* box-shadow: inset 0 0 0 1px rgba(0, 0, 0, 0.1), 0 1px 4px 0 rgba(12, 12, 13, 0.1) !important; */
    transition: box-shadow 100ms !important;
}
.Grid td > a.Bookmark :first-child:hover, .Grid td > a.Folder :first-child:hover, .Grid td > a.Back :first-child:hover {
    border-radius: 6px !important;
    box-shadow: inset 0 0 0 1px rgba(215, 215, 219, 0.3), 0 0 0 5px #D7D7DB !important;
    /* box-shadow: inset 0 0 0 1px rgba(0, 0, 0, 0.1), 0 0 0 5px #D7D7DB !important; */
    transition: box-shadow 150ms !important;
}
.Grid td > a > div:last-child {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Ubuntu", "Helvetica Neue", sans-serif !important;
    font-size: 12px !important;
    border-top: 0 solid rgb(51, 51, 51) !important;
    white-space: nowrap !important;
    text-overflow: ellipsis !important;
    padding: 7px 5px 0 !important;
}
