### ISSUE TITLE
quick dial eats tabs

### ISSUE THREAD

**Issue by marnur** [MatMoul/quickdial-webext#147]
After rebooting firefox, instead of the first three pinned tabs with sites, the quick dial page opens. Those tabs that go further open normally.
The first three tabs can be returned by pressing Alt + ←
Backspace (back button in the browser).

**Comment by marnur** [comment]
Installing "Startpage timeout" from old 500 to new 0 fixed the error.
Version 0.1.19

**Comment by MaximilianKohler** [comment]
>Installing "Startpage timeout" from old 500 to new 0 fixed the error.

A web search for "Startpage timeout" gives nothing. Presumably you mean you changed a value in about:config? Yet there are no results there for "startpage". 

What exactly did you do to fix this?

**Comment by marnur** [comment]
> What exactly did you do to fix this?

This line is located in the add-on settings. I right clicked on the add-on tabbed main page and you will find this line in the settings drop-down menu.
