### ISSUE TITLE
Quick Dial not working when opening a new window by CTRL + N

### ISSUE THREAD

**Issue by zal-ua** [MatMoul/quickdial-webext#155]
Quick Dial works in new tabs, but when I open a new window by pressing CTRL + N, I see a blank page.

![Screenshot_99](https://user-images.githubusercontent.com/10294714/83911139-73db0580-a774-11ea-9d4f-8a5a2e04faa9.png)

Any help would be appreciated.

**Comment by MatMoul** [comment]
Is it still relevant?

**Comment by zal-ua** [comment]
Yes, but now I don't think it's the problem with Quick Dial. I installed FVD Speed Dial and it does the same from time to time. So it's either Firefox issue or my own unique case.

**Comment by MatMoul** [comment]
@zal-ua Thanks for your feedback, I close the issue
