### ISSUE TITLE
FF77 - QD keeps losing bookmarks. Shows the QD setup page with no bookmarks

### ISSUE THREAD

**Issue by Twolane2** [MatMoul/quickdial-webext#156]
Firefox77, Quick Dial keeps losing the bookmarks I set up. Nothing shows but a blank page and the background colour. It did this in other versions of FF as well. I no sooner load all the bookmarks again, and a day later, they're gone and the Quick Dial page is blank again.

Frustrating, to say the least.

I've disabled extensions. That isn't the problem with my Quick Dial. Disabling extensions doesn't do anything to fix the disappearing problem.

It's the same on all three of my laptops. All the QD bookmark entries are gone.

**Comment by MatMoul** [comment]
Is that still on?

**Comment by Twolane2** [comment]
I have no idea. I've been using something else since I had this problem with yours.
