### ISSUE TITLE
Firefox dev 85.0b2 extra elements appeared

### ISSUE THREAD

**Issue by ilyousha** [MatMoul/quickdial-webext#161]
![screenshot-c280f32e-d5f3-40c5-9b7b-17c0700af0cb-2020 12 17-22_35_46](https://user-images.githubusercontent.com/10628881/102534746-5211f200-40b8-11eb-9d0d-d4070875b4ab.png)
Extra elements have appeared, is this due to the beta version of the browser?

**Comment by MatMoul** [comment]
Thanks for feedback...

I hope this is a beta error...
I'm missing time to update this project but I use it and when I'm impacted I made the necessary...

**Comment by ilyousha** [comment]
Thx
