### ISSUE TITLE
Grid is wider than it used to be 

### ISSUE THREAD

**Issue by agilob** [MatMoul/quickdial-webext#164]
I have 4x5 grid which used to fix on one screen, but after update to 85 the grid has now a horizontal scroll, 1/3 of the last column doesn't fit in the screen without scrolling.

Broken since Fx 85

**Comment by Planet6** [comment]
I have similar problems with 85. Plus there are some white stripes on the left. See picture
<img width="209" alt="2021-01-26 23_33_29-Quick Dial — Mozilla Firefox" src="https://user-images.githubusercontent.com/27927871/105914739-06475680-602f-11eb-9271-c406954fe119.png">

**Comment by harbourlad** [comment]
I have exactly the same problem since 85.0

**Comment by Hiromacu** [comment]
![ScreenShot01](https://user-images.githubusercontent.com/12880430/106024235-dc8e3e00-60c7-11eb-9a80-69ca579399a0.png)
Same problem here.

**Comment by MatMoul** [comment]
Temporary fix :
https://github.com/MatMoul/quickdial-webext/issues/162#issuecomment-767738932
And my reply :
https://github.com/MatMoul/quickdial-webext/issues/162#issuecomment-768491335

**Comment by agilob** [comment]
Thanks, I feared the addon has been abandoned.

**Comment by MatMoul** [comment]
I'm just to busy to work on it...
But when I'm impacted, I need to take time :(

**Comment by MatMoul** [comment]
You can orce update your addons and reset `dom.menuitem.enabled` flag.
I've rewrited the context menu with the limitations of the current API.
Now all is grouped in the child menu "Quick Dial"

**Comment by agilob** [comment]
Thanks
