### ISSUE TITLE
Firefox took forced update, no longer works in firefox 85.0 64bit

### ISSUE THREAD

**Issue by aidengray** [MatMoul/quickdial-webext#166]
Does not work in firefox 85.0 64bit.  Only option firefox gives is to remove.
I can modify existing bookmarks but not create new ones.

Thank you,

**Comment by aidengray** [comment]
I should of read deeper before posting. 
Please see
https://github.com/MatMoul/quickdial-webext/issues/162

**Comment by dueddel** [comment]
Another note on the latest FF update (as of writing this is 85.0).
Not only you can't edit existing quick dial links in the grid being shown in a new tab. There also has been added some weird menu icons in the upper left corner of the quick dial page.

<img width="181" alt="Bildschirmfoto 2021-01-28 um 10 00 12" src="https://user-images.githubusercontent.com/436636/106114446-d93e9500-614f-11eb-894b-4d9a20ddd9c2.png">

The good news, though: The menu icons can be easily removed by adding some simple CSS like `display: none` to both `<menu>` items.

<img width="284" alt="Bildschirmfoto 2021-01-28 um 10 01 23" src="https://user-images.githubusercontent.com/436636/106114461-db085880-614f-11eb-8844-c872e23b587b.png">

**Comment by minzak** [comment]
Same bug!

**Comment by glompie** [comment]
![Knipsel](https://user-images.githubusercontent.com/33806903/106341274-efa63700-629c-11eb-954f-946d20589edf.JPG)

**Comment by MatMoul** [comment]
You can orce update your addons and reset `dom.menuitem.enabled` flag.
I've rewrited the context menu with the limitations of the current API.
Now all is grouped in the child menu "Quick Dial"
