### ISSUE TITLE
Graphics bug

### ISSUE THREAD

**Issue by Ainson** [MatMoul/quickdial-webext#167]
After the Firefox 85 update, some lines have appeared in the background, forcing all the dials to be shifted to the right, see picture.
![Quick dial graphics issue](https://user-images.githubusercontent.com/20935242/106398293-4bde9780-6412-11eb-8bc6-4b15ec4656a4.jpg)

Any ideas? (Windows 7 64)

**Comment by de-es** [comment]
The latest release (0.1.20) fixed that.

**Comment by Ainson** [comment]
Just updated, and it's indeed fixed. Thanks.
