### ISSUE TITLE
Thx for the Quickdial fix /donation question

### ISSUE THREAD

**Issue by Planet6** [MatMoul/quickdial-webext#168]
Thanks MatMoul

is your support Bitcoin adress @ https://matmoul.ch/supportme still valid?

**Comment by MatMoul** [comment]
Hi, yes it is...
Thanks for your proposition

**Comment by Planet6** [comment]
I don't have much (lost my job recently) but can share some btc. as a thank you for this nice addon.

**Comment by MatMoul** [comment]
First, I did this project for myself and ended up sharing it ...
I'm not expecting money ...
Keep your Bitcoin and give it to me if the price explodes :p
