### ISSUE TITLE
Fixed tile Width and Height

### ISSUE THREAD

**Issue by Acid-Crash** [MatMoul/quickdial-webext#17]
Current configuration lets to choose number of rows and columns.
Such approach has its benefits but also has some side effects.
The chosen config remains same despite window size. 
Because of this on low width windows tiles become tiny and hard to recognize because extention tries to fit predefined column number into smaller window size.
Also this behavior makes hard to use custom tile images.
Image proportions are changing based on window size/row-column number so its barely possible to pick one image size suitable for multiple configs.
My current config is  4 rows and 8 columns 

I suggest letting user set tile width instead of number of columns. 
If user tends to get desired number of columns it is still possible (by changing width and observing how many tiles are fitting into one row).
Tile width should remain fixed when window size is changed.
Based on width height should be calculated by extension itself. 
Obviously because of the fixed dimensions there is a possibility that on low window sizes number of tiles in one row could be less that in full screen (tiles will be "floating" to next row).
However on the bright side tiles will remain recognizable in any window size. Also such config will help choosing standard size for custom tile images and hopefully for "capture in new tab" image feature (currently its still stretches images).

**Comment by MatMoul** [comment]
In my idea, I prefer using rows and columns because each links are always on the same place.
And at this time, it's seem too much complicated to provide an alternative display.
Concerning the captures methods, I'll to provide more parameters in the config but I need to make some other works before.

**Comment by Acid-Crash** [comment]
Thx for the quick reply.
It's a pity that new method is hard to implement.
Well here is additional idea.
If you prefer fixed position for each tile maybe y2ou could add some kind of minimum tile size.
After this size is passed horizontal scroll could be used. 
In this case tiles will stay on their original position and their size will remain recognizable.

**Comment by MatMoul** [comment]
I have some ideas for the future that can resolve #6 and your request but I need to make a hard refactory of my dial page. This is for a next major version.
Now I have other priorities on my background script before to do that.
But ideas are always welcome.

**Comment by berlihingen** [comment]
Yes, that's why I love this addon over similar - Everything in its Right Place, whatever size of window.

**Comment by MatMoul** [comment]
Sorry, I close this issue because I can't provide a good solution now.
You can try to reopen this issue in 6 months
