### ISSUE TITLE
new dials disappear in few seconds + wrong pathes

### ISSUE THREAD

**Issue by baxer996** [MatMoul/quickdial-webext#171]
hi guys.
after last update (30.01.2021 / ver. 0.1.20) - there is a new strong bug =(
NEW created Dials disappear in few seconds (we see them and then poof!... nothing)
+ in bookmarks they don't automatic added in "Bookmarks/Quik Dial" path, instead of it they are moved in default bookmarks path of Firefox.
(everything is fine with the old ones, this only affects newly created)

wish a new patch =) ty Mat!

**Comment by MatMoul** [comment]
First time for this issue...
What's your settings in "Context Menu" - "Quick Dial" - "Quick Dial Settings" and in tab "Grid" and setting "Root Folder"?
"Quick Dial" by default...

**Comment by baxer996** [comment]
Screenshot attached.

And I find what the problem was... (why new dials all disappear)

I use for years very good firefox addon "DEFAULT BOOKMARK FOLDER" (DBF) (author: Teddy Gustiaux) 
(because firefox by default always move all new bookmarks (CTRL+D) to "other bookmarks" folder. this addon fast fix it. simple and works great!)
and i see that (DBF) takes ALL new created dials (even created by your addon) and move it to default folder in bookmarks.
if i disable this addon (DBF) - Quick Dial works correctly!  
may be both addons use same mechanic with working with new bookmarks?...

![scr_01](https://user-images.githubusercontent.com/31290048/106945342-b9533680-6738-11eb-886c-d84c67735eb4.png)

**Comment by MatMoul** [comment]
Thanks for your feedback..
Not a first time that an other addons enter in conflict with Quick Dial...
Closing the issue but you're welcome to reopen it...
