### ISSUE TITLE
Tiles partially dissappear

### ISSUE THREAD

**Issue by scienmind** [MatMoul/quickdial-webext#18]
Not easily reproducible, but happened to me a couple of times:
 - Navigate in and out of Quick Dial's subfolders:
 - Suddenly, on the main page of Quick Dial, only 4 first items (out of full 5x5 grid) are shown 

It recovers back to normal after browser restart.

Console output:
`TypeError: app.node.children[i] is undefined  dial.js:398:1`

FF 56
QD 0.1.5

**Comment by MatMoul** [comment]
I can not reproduce but I will try to find what's the problem in the code with your output result.
Can you give me more infos ?
What's your 4 and 5 items (folder, bookmark) ?
And if you can, provide me their titles ?

**Comment by scienmind** [comment]
Here's a screenshot of the layout:
![image](https://user-images.githubusercontent.com/11633330/31998018-d8d196ee-b996-11e7-8fe9-fd4133db3ec8.png)

It happened to me couple of times since the original report. Unfortunately I can't reliably reproduce it, it spontaneously happens after in/out subfolder navigation.

**Comment by MatMoul** [comment]
Thanks for your return, nothing special...
Can you give the list of your addons? Looking issue #23 it's a possible way.

**Comment by scienmind** [comment]
I'm pretty sure it's not related to other extensions. 
I do have couple of extensions, but nothing similar to what mentioned in #23. Beyond https everywhere and ublock, nothing is messing with pages really.

I'll keep it in mind though, and will try to provide more info the next time it happens

**Comment by MatMoul** [comment]
Ok, in a future beta release I'll handle the error mentioned on the first post and this will show we if this is only a tile that make this issue

**Comment by MatMoul** [comment]
@scienmind I don't have handled the error mentionned but are you still experiencing your problem in version 0.1.6?

**Comment by scienmind** [comment]
I wasn't able to reproduce it for a while now (before 0.1.6). 

Should I close it for now (reopen if resurfaced)?

**Comment by MatMoul** [comment]
I close, reopen if needed
