### ISSUE TITLE
Annoying content in the location bar

### ISSUE THREAD

**Issue by philippetev** [MatMoul/quickdial-webext#19]
I get this in the location bar every thime when I open new tab:
moz-extension://69eedb90-b395-a049-a1b6-7189d8ef68ce/dial
Is there any way to be fixed? 
Firefox 56.0.1 macOS

**Comment by MatMoul** [comment]
Just wait ff57, this will be fixed by mozilla.
But for child folder page, the moz-extention url will still showing up...

**Comment by MatMoul** [comment]
ff57 is out, I close the issue
