### ISSUE TITLE
[Feat.Request] Clear address bar after opening new tab or page

### ISSUE THREAD

**Issue by jnko** [MatMoul/quickdial-webext#2]
Thank you for this very good extension! It instantly replaced SpeedStart for me.

There's one little thing I would be glad to see: 
After opening a new page or tab it would be really fine if the address bar could be focused and cleared. 

Every time I type STRG-T the cursor is placed behind "moz-extension://d7e8c9eb-8265-4423-944d-1a1b02e3aed6/dial" and this way it is not possible to use the address bar for directly entering a URL or search something without typing STRG-A, DEL, Url first

I guess this is just a one-liner and not really difficult add.

**Comment by MatMoul** [comment]
What version of Firefox do you use?
Before 57, it' bug of firefox...

**Comment by jnko** [comment]
I'm running FF56 on Arch, so yes it's before FF57. Do you have more infos about the FF bug? 

Anyway is it is a FF bug lets close this issue.  Thanks anyway
