### ISSUE TITLE
Feature Request: tiles images - keep proportions + transparency + borders

### ISSUE THREAD

**Issue by berlihingen** [MatMoul/quickdial-webext#20]
I'm using mostly page logos (transparent png) for tiles - now when you add it, image automatically fills the tile, giving ugly unproportional results. Can it be just **centered (not stretched) if size is smaller than tile**?
And two more design suggestions:

- tiles transparency (level);
- tiles border disable/enable/thickness

Thanks
P.S. Love this addon, two of reasons: bookmark based tiles (simply to organize, backup, sync) and tiles keep their places. Please, keep it this way :)

**Comment by MatMoul** [comment]
I'll work on this feature on a next major release.

**Comment by MatMoul** [comment]
Is the V 0.1.9 resolving all your request ?
If yes, close the issue
If no, give me what are missing

**Comment by berlihingen** [comment]
Perfect work, all the way! Thank you.
