### ISSUE TITLE
Settings gone

### ISSUE THREAD

**Issue by berlihingen** [MatMoul/quickdial-webext#23]
At office I have "Master Password" addon which is set to logout&minimize after time of inactivity; so after I logged back, my Quick Dial page was in default shape - all customization lost (except of bookmarks). I compared actual profile with backup and found the difference: storage.js in quickdial@matmoul.com - about 2mb actual and over 11mb in the backup. Overwriting returned all my settings, but then I tried to reproduce glitch - successful - this time storage.gs fell to just 2 bytes.
Any connections with Master Password, or...?

**Comment by MatMoul** [comment]
Can you give your addon link of your Master Password ?
Is it compatible with ff57?

**Comment by berlihingen** [comment]
[https://addons.mozilla.org/en-US/firefox/addon/master-password/](url)
no, it going to die with 57, but I'm not sure this addon is culprit

**Comment by MatMoul** [comment]
Thank you for your return, but how you can see, I'm submerged by issues that requires more attention...
I close the issue because it's possible that is linked to #18
But if you have more infos, you can reopen this issue...

**Comment by berlihingen** [comment]
understood, ok
