### ISSUE TITLE
Need a option to set screenshot delay

### ISSUE THREAD

**Issue by hdd60311** [MatMoul/quickdial-webext#25]
Some websites need more time to load page completely, a example website http://www.weibo.com/asrac?is_all=1
and the thumbnail is this ( use "Capture in a new tab")
![default](https://user-images.githubusercontent.com/5089290/32013242-f5e4fc70-b9ec-11e7-9222-796e70f32b20.png)

btw the screenshot quality isn't very good, need to improve it.

**Comment by MatMoul** [comment]
This is certainly why many developper has stopped his developpement...
The new addons in Firefox are very restrictive...
I try many solution but no one repply on each website...
Now, I try to test all the solution I've found and I'll provide a best solution in the future.

**Comment by scienmind** [comment]
The delay option certainly would fix "capturing in new tab". 

[Bookmarked Dial](https://addons.mozilla.org/en-US/firefox/addon/bookmarked-speeddial/) does so, and capturing with 1-2 sec. delay works well.

**Comment by ZatsuneNoMokou** [comment]
A setting to set the delay would be good, depending on computers and connections, 2sec could be short in somes cases (or some slow hosted websites, eventually)

**Comment by MatMoul** [comment]
Option are added in V 0.1.9 (2s by default)
You can edit the value in Quick Dial settings
