### ISSUE TITLE
Feature Request: option to disable context menu items

### ISSUE THREAD

**Issue by Acid-Crash** [MatMoul/quickdial-webext#26]
Some users like when their context menu remain short and simple.
Could you please add an option to toggle appearance of "Add to Quick Dial" item in context menu (regular right click on page and hovering over the link)

**Comment by fernandosantucci** [comment]
Just execute this method before create the `dial.PageMenu` and `dial.ItemMenu` in the line 167 at **/src/js/dial.js**. This method only affect the Context Menus of this Extension, not all Firefox environment.
[https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus/removeAll](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus/removeAll)

**Comment by MatMoul** [comment]
I'll provide soon an option in Quick Dial settings

**Comment by MatMoul** [comment]
0.1.11 is out with a new setting for this feature (on the bottom of the page settings)...
