### ISSUE TITLE
Editing URLs does not update bookmarks

### ISSUE THREAD

**Issue by scienmind** [MatMoul/quickdial-webext#27]
Steps:
1. Edit item's URL (via right click -> properties), save the change
 - Actual result: the correlated bookmark's URL doesn't change 
 - Expected result: Bookmark is updated

Issue exists the other way around as well: Update bookmark's URL via bookmark manage -> no effect on the Quick Dial's item.
(Only if edited bookmarks are moved to another folder and then moved back, then Quick Dial will recognize the change)

Related: #4 #5 

Just spend an hour updating links via Quick Dial, to find out that those changes are not applied to bookmarks and unsyncable to other devices, and I need to start all over ☹️ ...

**Comment by MatMoul** [comment]
I'm now testing many storage and sync features...
I've put it aside for the moment but work is in progress

**Comment by MatMoul** [comment]
Version 0.1.7 should fix this issue.
Reopen if not

**Comment by scienmind** [comment]
Fixed, but in one direction only, see #37
