### ISSUE TITLE
Bookmark added loop after delete

### ISSUE THREAD

**Issue by rbrtjr** [MatMoul/quickdial-webext#29]
Delete "quick dial" from bookmark manager starts a "loop" adding (restoring) deleted item

**Comment by MatMoul** [comment]
I've a bad side effect when I delete or paste to many items on the quick dial folder.
I've a temporary solution for the next version.

**Comment by MatMoul** [comment]
Can you try the last version, it seem that's fixed...

**Comment by rbrtjr** [comment]
It´s ok now! I can delete, copy and paste bmarks now (but properties-images are not saved). I think could be a good think a save/restore feature.
