### ISSUE TITLE
Feature Request: Allow customizing root folder path

### ISSUE THREAD

**Issue by scienmind** [MatMoul/quickdial-webext#3]
Currently Quick Dial displays everything under "Bookmarks Menu/Quick Dial" folder. 

It would be useful to be able to select a custom per-existing bookmark folder to be used as Quick Dial's base folder (e.g. "Bookmarks Toolbar\Some Subfolder\Subfolder").

**Comment by MatMoul** [comment]
This feature will be comming before the release of ff57 but it's not in the priority.

**Comment by MatMoul** [comment]
Root folder customization is now supported in version 0.1.5.
I need to add some hint on how to use it...
You can use / to have the root of all bookmark.
Or /folder/folder/... to have a folder from the root.
Or folder/folder/... to have a folder from the Bookmars Menu

**Comment by scienmind** [comment]
Thanks!
Works for me :) 

However, for the best UX for "average user" there should probably be a "browse/select" button to let the user pick a folder from the Bookmarks tree.
