### ISSUE TITLE
Auto Refresh

### ISSUE THREAD

**Issue by YuriiBar** [MatMoul/quickdial-webext#30]
Please disconnect auto refresh. For example, some links can only work with a proxy and enabled in Add-ons by default auto refresh spoils snapshot from a link and its Title. I suggest automatically creating a snapshot and title for the link only when creating. In other cases, it is more convenient to do this only in manual mode. For example, I always adjust for title links, because web-generated page headers are not always informative and convenient in content. And their automatic change negates the design of Quick Dial. And, automatically changing the snapshot and title makes Add-ons "Xmarks Sync" work once again

**Comment by MatMoul** [comment]
Don't worry,
In the future, I'll add an autorefresh feature but I've added a setting that you can lock update of title per tile and a second setting for the picture comming.

**Comment by YuriiBar** [comment]
Thank you
