### ISSUE TITLE
Text encoding

### ISSUE THREAD

**Issue by Alexey71** [MatMoul/quickdial-webext#31]
Hi. Please fix text encoding  on previews and captions
Speed Dial - all in triangles
![333](https://user-images.githubusercontent.com/10572914/32231690-550c47f2-be67-11e7-9dda-3ed456af49f3.png)

Fast Dial - fine
![1111](https://user-images.githubusercontent.com/10572914/32231670-43a74084-be67-11e7-9f6e-7c03803f573b.png)

**Comment by Alexey71** [comment]
Test site
 http://tapochek.net/index.php
http://series40.kiev.ua/

**Comment by MatMoul** [comment]
Thanks for your return,
I'll try to work on it...

**Comment by Alexey71** [comment]
Hi. I try test version 0.1.6b1. Button "Capture here" fix my problem, but the quality of the previews is just awful. I have a 4x9 grid. After clicking this button, the preview image is excellent, but after a second it becomes poorly readable
