### ISSUE TITLE
Multiple duplicate folders creation while Restoring bookmarks

### ISSUE THREAD

**Issue by Acid-Crash** [MatMoul/quickdial-webext#33]
When using Restore bookmarks (from last backups files) in Library Firefox hangs because multiple "Quick Dial" folder is being created.
The only solution is to disable extension, use restore bookmarks and the re-enabling extension.
Tested on Win10 x64 latest Nightly and FF 56.0.2

**Comment by MatMoul** [comment]
@Acid-Crash Thanks for your return, need investigation...

**Comment by MatMoul** [comment]
Version 0.1.7 should fix this issue.
Reopen if not
