### ISSUE TITLE
How do you work with folders? (save, move, drag)

### ISSUE THREAD

**Issue by Just4code** [MatMoul/quickdial-webext#35]

**Comment by MatMoul** [comment]
Not sure what the question

**Comment by Just4code** [comment]
from the context menu, selecting 'Add to Quick Dial', then how do I select subfolder of Quick Dial?
Good Job by the way.

**Comment by MatMoul** [comment]
At this time, 'Add to Quick Dial' add tile to the main dial page.
You have 2 possibiliies to add or move it to a folder :
Add to a folder : copy the url and go to the folder page. right click and add a bookmark then paste the url.
Move to a folder : use the bookmark window and move your bookmarkitem.

**Comment by Just4code** [comment]
Got it. Hope in the near future it will be implemented properly.
Thanks, cheers
