### ISSUE TITLE
Editing bookmarks' URLs does not update Quick Dial's links

### ISSUE THREAD

**Issue by scienmind** [MatMoul/quickdial-webext#37]
While #27 is fixed, the reverse of it is not:

1. Create a new bookmark item; verify it is the same both in Quick Dial and in FF's bookamrks
2. Edit a part of a link using FF's bookmark manager
3. Verify changes saved:
 - in FF's bookmarks - address is updated
 - in Quick Dial the URL is not updated

FF v.56.0.2
QD v.0.1.7

**Comment by MatMoul** [comment]
Arg... One test i've not made

**Comment by MatMoul** [comment]
Fixed in 0.1.8

**Comment by scienmind** [comment]
Seems to be fixed, thanks!
