### ISSUE TITLE
Capture in a new tab

### ISSUE THREAD

**Issue by Alexey71** [MatMoul/quickdial-webext#38]
Hello.
Capture in a new tab - bad work. Stretched thumbnail. My monitore 21:9 (2560x1080)
Test URL - https://www.ebay.com/

Default
![2017-11-11 20 28 09](https://user-images.githubusercontent.com/10572914/32691837-0854bfbe-c71f-11e7-9815-dce39a733327.png)

Stretch
![stretch](https://user-images.githubusercontent.com/10572914/32691907-00a4fabc-c720-11e7-8bc5-18e88df2df9c.png)

Cover
![cover](https://user-images.githubusercontent.com/10572914/32691910-0c0ee444-c720-11e7-9fbe-b1512b2bc670.png)

Contain
![contain](https://user-images.githubusercontent.com/10572914/32691911-15007234-c720-11e7-994a-f41ff7d6f15b.png)

Center
![center](https://user-images.githubusercontent.com/10572914/32691913-1d005a1c-c720-11e7-91db-dfac78ede4e5.png)

**Comment by MatMoul** [comment]
This is due to the ratio I use for snapshot.
In the future, I'll provide a best solution.

**Comment by ZatsuneNoMokou** [comment]
Could it be possible to add a delay? I have Youtube page that can't fully load

**Comment by scienmind** [comment]
> Could it be possible to add a delay?

Tracked here: https://github.com/MatMoul/quickdial-webext/issues/25

**Comment by MatMoul** [comment]
Refresh your tiles and give me return with version 0.1.9

**Comment by Alexey71** [comment]
0.1.9 broke grid
![2017-11-18 12 48 31](https://user-images.githubusercontent.com/10572914/32979043-f3c7614c-cc5e-11e7-8916-b91ee041a5f7.png)

0.1.8
![2017-11-18 12 49 18](https://user-images.githubusercontent.com/10572914/32979045-fa5612e2-cc5e-11e7-86ff-0f89b6ce6109.png)

**Comment by Alexey71** [comment]
Capture in a new tab not fix

**Comment by Alexey71** [comment]
What happened to the grid :?
v0.1.9
![2017-11-18 12 48 31](https://user-images.githubusercontent.com/10572914/32979179-6f3d4592-cc61-11e7-8e1c-5f6dcb1a5bdf.png)

v0.1.8
![2017-11-18 12 49 18](https://user-images.githubusercontent.com/10572914/32979181-7724648e-cc61-11e7-8f12-9b583dc8fd1a.png)

**Comment by MatMoul** [comment]
In 0.1.9, I've introduced an auto ratio calculation based on the cells count.
0.1.10 will comming with a new settings that you can set your own ratio.

**Comment by MatMoul** [comment]
0.1.10 is out, you need to retreave the default ratio.
But now you can edit the ratio in quick dial settings on grid page (4/3 by default).

**Comment by Alexey71** [comment]
Fine
