### ISSUE TITLE
Duplicated Quick Dial folder while Restoring bookmarks

### ISSUE THREAD

**Issue by Acid-Crash** [MatMoul/quickdial-webext#39]
Continuation of #33 
Issue has been partially fixed (single duplicate is still here and luckily there is no FF hangs).

When using Restore bookmarks (from last backups files) in Library, Firefox creates single duplicate of  "Quick Dial" folder (empty one) as last item in bookmark list. The correct "Quick Dial" (proper folder that has been used by extension) folder is also present at its correct place with all its content and is used by extension if new tab is opened.
Deletion of newly created empty "Quick Dial" folder doesn't have any negative effect on extension behavior. 
Tested on Win10 x64 latest Nightly and FF 56.0.2

**Comment by MatMoul** [comment]
I can't reproduce...
Are you sure that the second folder are not in your backup?

**Comment by Acid-Crash** [comment]
Double-checked it again.
Still happens to me on latest Nightly with unsigned to Firefox Sync clean profile
Steps done to reproduce.
- create clean profile.
- install quick dial 0.1.8.
- Add single bookmark to Quick Dial folder.
- close Quick Dial tab
- Create backup via Library - Import And Backup - Backup
- Restore from backup (created from previous step)
- New Quick Dial folder (empty) appears. Old with single bookmark in it is also present

**Comment by MatMoul** [comment]
I don't encouter this issue on my computer.
Need more investigation
