### ISSUE TITLE
Refresh layout according to changes in bookmarks folder

### ISSUE THREAD

**Issue by scienmind** [MatMoul/quickdial-webext#4]
Reproduction steps:
1. Put several bookmarks/folders inside "Quick Dial"
2. Open Quick Dial (New page)
3. All items are loaded properly
4. Open FF's Library and delete an item from "Quick Dial" folder
Actual result: Empty space displayed instead of removed item
Expected result: Layout adjusts to reflect updated contents of the folder, without blank spaces.

**Comment by MatMoul** [comment]
This is the way that work because when you delete an items, I don't wan't all my item move...
But in the future I can provide an option for this.

**Comment by scienmind** [comment]
I see your point, and the current behavior is somewhat consistent with the default FF's new page pinned items, but it is at odds with other "speed dials" (Opera, Vivaldi, and some popular extensions).

Moreover, https://github.com/MatMoul/quickdial-webext/issues/5 will allow to sync layouts using build-in FF sync and have a consistency across multiple devices without having to rearrange each one separately (you claimed this issue is somewhat-blocking #5)

**Comment by scienmind** [comment]
After #9 fix, the change (i.e. addition/deletion) in Bookmarks folder is only reflected by Quick Dial after browser restart.

**Comment by scienmind** [comment]
v.0.1.1 fixed the behavior described in the comment above. Now it's back as it was in the original report.

**Comment by MatMoul** [comment]
Is version 0.1.6 resolving this issue?

**Comment by scienmind** [comment]
I don't see any change in behavior. (Is there a config. option I'm missing?)

This issue is about allowing for an option for Quick Dial re-flowing items' order, based on changes (deletions/rearrangements) to bookmarks folder.

**Comment by MatMoul** [comment]
It must be fatigue ...
I misread the issue

**Comment by MatMoul** [comment]
Sorry, too many job to make a second implementation of deletion of items
