### ISSUE TITLE
Open in New tab option

### ISSUE THREAD

**Issue by loginitin** [MatMoul/quickdial-webext#40]
Please provide an option so that when a tab is clicked the url opens in a new tab. It would save a lot of time.
Thanks :)

**Comment by MatMoul** [comment]
At this time, you can use middle click or right click and open in new tab.
I'll add this feature in the future but I've other priorities

**Comment by painter73** [comment]
would also LOVE my saved pages to 'open in a new tab' :) 
Well done MatMoul, this is an excellent replacement from my non-compatible fast dial. Look forward to this future enhancement.... THX!

**Comment by glompie** [comment]
Fast Dial had the option to open in the same tab. If you want a new tab just click the plus sign in the browser (or ctrl+T). I want to be able to look at a website. Click the Quick Dial sign and look at another site. Without opening two tabs (or after 10 min. 30 tabs).

**Comment by MatMoul** [comment]
In V 0.1.13 you can set to open bookmarks or folders in a new tab...
Quick Dial Settings - Grid - Open...
