### ISSUE TITLE
Can't open dials with local links (f.e.: file:///C:/1/index.html)

### ISSUE THREAD

**Issue by ValSergeev** [MatMoul/quickdial-webext#41]
Win7/ Firefox 57.0 (64-bit)/ Quick Dial 0.1.8

**Comment by MatMoul** [comment]
Not sure that is possible with current restriction on ff57

**Comment by fernandosantucci** [comment]
In Linux Ext4 file system I also can't open URLs for local links.
Ubuntu 16.04 LTS 64-bit
Firefox v57

**Comment by MatMoul** [comment]
This is definitely not possible with current version of FF
We need to wait update and see if the api offer a solution in the future.
