### ISSUE TITLE
No tabs

### ISSUE THREAD

**Issue by Vlaholod** [MatMoul/quickdial-webext#42]
Could you tell me please what I am doing wrong ? After downloading and installing app , I open new tab and not boxes with sites, just grey window... How can I add new links ? 
![2017-11-16_19-28-53](https://user-images.githubusercontent.com/30910820/32902792-6cb39b9a-cb04-11e7-8dfb-521aa68a93b1.jpg)

**Comment by MatMoul** [comment]
Quick Dial start with an empty page.
You have 3 methods to add a bookmark or folder :
On a webpage, right click and on the menu choose "Add to Quick Dial"
On Quick Dial, right click and on the menu choose "Add" -> "Bookmark or folder"
And with the firefox bookmarks, you can add what you want on the Quick Dial folder.

**Comment by Vlaholod** [comment]
Huge thx m8 ! Got it !
