### ISSUE TITLE
Transparent Background in Hover Event of cells not work

### ISSUE THREAD

**Issue by fernandosantucci** [MatMoul/quickdial-webext#44]
I want set the background-color of cell to White and when hover the mouse over the background will be transparent to cells with transparent PNG logo images, reveling the page background-image.

However, the hover transparency just work whether the cell background also is defined as transparent.

Ubuntu Linux 16.04 LTS 64-bit
Firefox v57
Quick Dial v0.1.8

![captura de tela de 2017-11-17 10-46-40](https://user-images.githubusercontent.com/5784007/32948023-e9f1de0c-cb84-11e7-91d5-27cc4ab9aefc.png)
![captura de tela de 2017-11-17 10-55-45](https://user-images.githubusercontent.com/5784007/32948573-dc768898-cb86-11e7-987d-7d507fa1dbe3.png)

**Comment by MatMoul** [comment]
I'll correct this bug soon

**Comment by MatMoul** [comment]
V 0.1.9 is out, reopen issue if needed

**Comment by fernandosantucci** [comment]
Thank you for quick fix!
