### ISSUE TITLE
non-standard Tiles aspect ratio (on high column number)

### ISSUE THREAD

**Issue by Acid-Crash** [MatMoul/quickdial-webext#46]
After last update (0.1.9) aspect ratio has become barely usable. The tiles height is too small.
I'm using (Rows x Columns) 4x8 and 3x8 setup. My resolution is 1920*1080.
Here is an example of tile aspect ratios I get when using the following setup.
![12](https://user-images.githubusercontent.com/32600318/32980986-73ebdec4-cc79-11e7-973a-e8c0d1aa706a.jpg)
![11](https://user-images.githubusercontent.com/32600318/32980985-73cfc20c-cc79-11e7-841e-f52511429497.jpg)

The more-less usable aspect that I was able to get is when number of columns was decreased to 6.
![16](https://user-images.githubusercontent.com/32600318/32980993-8aa1a946-cc79-11e7-90ab-ebfa087e86ea.jpg)

But with this config tiles are just to big for me. 
I've also noticed that aspect ratio also reacts to number of rows as well making it ever more troublesome.

Is it possible to fix aspect ratio for config with high column number?
Additionally this issue can be removed if user had an option to pick preferred tile aspect ratio via extension settings. The most common aspect ratios (4x3, 16x10, 16x9) could be more than enough for this.

**Comment by scienmind** [comment]
related:  https://github.com/MatMoul/quickdial-webext/issues/38#issuecomment-345432133

And I have the same aspect ratio issues with v.0.1.9, only "squished" a bit differently:
![image](https://user-images.githubusercontent.com/11633330/32982102-b7811a56-cc87-11e7-8b3d-7c54110e87d1.png)

**Comment by MatMoul** [comment]
In 0.1.9, I've introduced an auto ratio calculation based on the cells count.
0.1.10 will comming with a new settings that you can set your own ratio.

**Comment by MatMoul** [comment]
0.1.10 is out, you need to retreave the default ratio.
But now you can edit the ratio in quick dial settings on grid page (4/3 by default)
