### ISSUE TITLE
Translated to Brazilian Portuguese (pt_BR)

### ISSUE THREAD

**Issue by fernandosantucci** [MatMoul/quickdial-webext#48]
Follows attached the file "messages.json" translated to Brazilian Portuguese to folder (/src/_locales/pt_BR). I only rename to extension (.txt) to allow attach it.

If you want translate for new updates, let me know how to proceed. If can I pull request or not, ok?!

[messages.json.txt](https://github.com/MatMoul/quickdial-webext/files/1485531/messages.json.txt)

**Comment by MatMoul** [comment]
No problem, you can make a PR

**Comment by fernandosantucci** [comment]
Pull Request #61 submited, can close it.

**Comment by MatMoul** [comment]
Thank you
