### ISSUE TITLE
Feature Request: Option to use stored selected image(logo) by default when URL updated.

### ISSUE THREAD

**Issue by ALEXGREENALEX** [MatMoul/quickdial-webext#50]
For example I used some logo image for some site, and if site will change URL I must change it too in cell, add-on will make new site screenshot. Now is impossible to save custom cell picture/logo.

**Comment by MatMoul** [comment]
I'll provide a lock feature for the image in a next release.

**Comment by MatMoul** [comment]
In version 0.1.11 you have a new setting on tile for locking image.
Close the issue if the I reply to your request...

**Comment by MatMoul** [comment]
@ALEXGREENALEX Not sure if my previous message concern you issue...
When rereading "Now is impossible to save custom cell picture/logo", I've resolved an issue in 0.1.12 for saving custom image.

**Comment by ALEXGREENALEX** [comment]
Big thanks, I hope it will very useful for a lot of users)
