### ISSUE TITLE
Bug: Fresh install, add items and it's not possible to drag it

### ISSUE THREAD

**Issue by MatMoul** [MatMoul/quickdial-webext#52]
After a fresh install and adding some folder, it's not possible to move it before closing and reopening the tab.

**Comment by vertigo220** [comment]
I just started using QD and experienced this as well. Thought at first they couldn't be rearranged and was very disappointed, then happened to close and reopen it and accidentally dragged one. This is in Waterfox 56.1.0 x64 on Win 10 x64 in case that helps.

**Comment by MatMoul** [comment]
Thank's for return, I need to work on it....
But I wish the days were longer

**Comment by MatMoul** [comment]
Fixed 0.1.17
