### ISSUE TITLE
It would be nice to make an option for the open button in the current tab ...

### ISSUE THREAD

**Issue by AlexSHB** [MatMoul/quickdial-webext#55]
When you click on the button "Quik Dial", a new tab opens, and the old one has to be closed, as unnecessary. It is not comfortable. To do this, there is a "+" button, which opens a new tab with QD links...

**Comment by glompie** [comment]
That's what I thought....

**Comment by MatMoul** [comment]
I'll over it if this is possible.
Look at #15
