### ISSUE TITLE
Feature Request: Add option for centralizing rows vertically

### ISSUE THREAD

**Issue by scienmind** [MatMoul/quickdial-webext#6]
Setting: Grid layout 5x5, 24 items; one sub-folder has 3 items
The main grid centered properly according to the window size, however, the sub-folder is centered as a full 5x5 grid, even though it has only 3 items, so the single present row is displayed on the top of the page.

Request: Add an option to center the grid dynamically, based on the number of rows actually populated by items. 
The setting will still define the maximum grid limits.

**Comment by MatMoul** [comment]
It's hard to code it, so not now but perhaps in the future

**Comment by MatMoul** [comment]
Sorry, I close this issue because I can't provide a good solution now.
You can try to reopen this issue in 6 months
