### ISSUE TITLE
There is no option for the removal of empty pages

### ISSUE THREAD

**Issue by UltimateUser** [MatMoul/quickdial-webext#60]
After removing all bookmarks/folders from a page the addon does not support a complete removal of the page itself resulting in visible empty pages when the users scrolls down from the initial page.
Important - The addon should add the possibility to remove the empty pages but not do that automatically, otherwise, empty pages might be deleted involontarily when grid properties are changed.

**Comment by MatMoul** [comment]
I'm not sure I understood.
It is in the case where an empty page is between 2 existing pages?
