### ISSUE TITLE
[bug] Setting as home page, but Firefox opens to a blank tab

### ISSUE THREAD

**Issue by Scharfestahl** [MatMoul/quickdial-webext#62]
I've been using this extension on two machines, and on both of them after a few opens, this does not open up as my home page anymore. Also when pressing the home icon while on a website, it does not load up the speed dial. Let me know if I can help with additional information if needed. Thanks!

**Comment by MatMoul** [comment]
Not sure what the problem...
Do you use firefox sync account ?
If yes, look at the issue #21

**Comment by Scharfestahl** [comment]
Thanks for the response! I think issue #21 might have been what the problem was. When I click set on start page, I notice that the URL is slightly different so I assume it is syncing my other computer's URL which is different. Sorry about posting about a known issue, I went through the forum and didn't see the post. I thought this might have been something that was happening to just me.

I will test to see if the fix sticks. Thanks!
