### ISSUE TITLE
Infinite Loop with Separator - Firefox Hangs

### ISSUE THREAD

**Issue by Tralen** [MatMoul/quickdial-webext#63]
Greetings,

I would like to report that an infinite refresh cycle occurs when there is a separator in the folder and Quick Dial tries to create an image for it. In a computer with limited resources, I had to forcefully kill Firefox twice to escape out of it.

Maybe Quick Dial could be made to ignore separators?

Thank you.

**Comment by MatMoul** [comment]
Thanks for return.
This is a bug :(

**Comment by MatMoul** [comment]
Bug is resolved in 0.1.12

**Comment by Tralen** [comment]
Thank you, MatMoul.
