### ISSUE TITLE
Please change the icon

### ISSUE THREAD

**Issue by MHX792** [MatMoul/quickdial-webext#67]
The icon just does not fit the gray scale look of firefox' other icons. Please add a gray icon or add an option to select our own favicon.
Thanks

**Comment by MatMoul** [comment]
I need to do it but I'm not a designer and this take me time that I don't have now

**Comment by MatMoul** [comment]
I tag to help wanted, if anyone is motived to provide images...

**Comment by MHX792** [comment]
What resolutions do you need? I will do that if I find some free time.

**Comment by MatMoul** [comment]
Actually, I have two sizes, 24x24 and 32x32 but it would be nice to have a 16x16.
The files are located in /src/img
@MHX792 If you want, I assign you this issue and I leave you to manage it if other people comming to participate.

**Comment by MHX792** [comment]
No need for that. I just created the icons. Both for the dark and light theme.

![screen shot 2017-12-04 at 22 24 00](https://user-images.githubusercontent.com/12123471/33576993-e312a5e2-d941-11e7-9f69-685d8e15315c.png)

Download them from here: 
[icons_quick_dial.zip](https://github.com/MatMoul/quickdial-webext/files/1528836/icons_quick_dial.zip)

**Comment by MatMoul** [comment]
Thank you for your contribution, I'll work on it for the next version

**Comment by MHX792** [comment]
One thought though: you should leave the current icon as it makes clear that quick dial is the successor of fast dial. Adding an option for the user to select the desired icon (classic, dark, or light one) is the better solution.

**Comment by MatMoul** [comment]
I agree to provide a setting for the desired Icon.
Currently, I allowed myself to use the Fast Dial graphics hoping to respect the license but in the future, I need to provide a separate graphic line.
Quick Dial is not Fast Dial 2 but Fast Dial was my favorite Dial...

**Comment by Acid-Crash** [comment]
Hi here, if were talking about the icon change maybe it would be better to replace current one with SVG instead of PNG

**Comment by MatMoul** [comment]
@Acid-Crash I never tested a svg, if this is working, it's certainly better than a png.

**Comment by Acid-Crash** [comment]
Actually it looks like one such icon is already present in Photon icon library (Top Sites 16)
https://design.firefox.com/icons/viewer/
And it has dart and light state

**Comment by MHX792** [comment]
Any ETA?

**Comment by MatMoul** [comment]
Sorry but no ETA, it's not a priority...
But I'm always open to contributions...

**Comment by MHX792** [comment]
You just need to replace the png files with the ones I created for you.
Will not take 3 min.

**Comment by MatMoul** [comment]
If this take 3 min for you, make a PR...
