### ISSUE TITLE
Lock Quick Dial Tab and open New Tab with another Page

### ISSUE THREAD

**Issue by FuGu21** [MatMoul/quickdial-webext#68]
Hello MatMoul, 
at first i would like to thank you for writing this Extension!

For the future.. would it be possible to lock the Quick Dial Page, so it can't be closed for example with CMD+W and the option to open a new tab with google for example. 

This are features fom the old addon Tab Mix Plus and it would be geat to have them in your Extension.

Greets Rainer

**Comment by Hiromacu** [comment]
Hi FuGu2,

- Locking QD: You can lock it using Pin Tab from the tab context menu. 
- optional New Tab: yeah it's a good idea. We can have QD as Home Page while you set a different New Tab.

**Comment by MatMoul** [comment]
@FuGu21 I'm not sure I'm fully understand the first request. Reading the reply of @Hiromacu Pin Tab can be a solution.
For the second request, API are availble on FF57+ but not on older version.
I'll try to implement it without breaking esr version.

**Comment by FuGu21** [comment]
Hi together... 
Thanks a lot Hiromacu... using Tab Mix Plus for years let me forget that this function onboard now!
And now, with the Extension New Tab Override it works somehow... if i open FF i've git my Quick dial Page... pin the Tab and when i open a new Tab it is Google Search...
