### ISSUE TITLE
All settings gone

### ISSUE THREAD

**Issue by Ainson** [MatMoul/quickdial-webext#70]
Opened Firefox today 57.0.2 (64-bit) and all the settings like thumbnails, order and everything else I had painstakingly set have disappeared.

**Comment by MatMoul** [comment]
Now, with more than 10'000 users, I've received less than 10 requests for data corruption.
It seem that is not Quick Dial but an other extention that crash Firefox or a very old harddrive that began to slow or have bad track.

Other infos on issue #59

**Comment by Ainson** [comment]
How can you be sure it's not Quick Dial responsible for the crash? After all, it's the QD file storage.js.corrupt that's corrupted. This happened after the computer was switched off by using the case main button (cold shutoff), where Firefox and Windows wasn't closed. No other programs gets messed up by doing this, so it's something with Quick Dial.

What's anyway needed is an easy way to back up settings, or at least explain how to do it manually.

**Comment by MatMoul** [comment]
@Ainson Ok the cold shutdown is certainly the raison...

I store the data with Firefox API but I need to save all images and the settings file can have many Gb.

Saving this file can take time with an old harddrive and if Firefox is killed, the storage file become corrupted.
I hope that Firefox would provide a more robust method in the future.

I'll try to provide a backup solution but I've currently other priorities for Quick Dial.
Actually, you can save your storage.js file.
