### ISSUE TITLE
how to set root to folder in bookmarks toolbar?

### ISSUE THREAD

**Issue by t7yang** [MatMoul/quickdial-webext#72]
as title

**Comment by MatMoul** [comment]
In Quick Dial Settings, at the bottom of Grid tab, You can use / in Root Folder field.
But I recommend you to backup your bookmarks before because "Quick Dial" update title of each bookmarks when it update the dial.

**Comment by t7yang** [comment]
Thank, it work. It is nice if add this instruction to add-on page :)

But I notice that every time after root folder setting changed make speed dial page broken, showing blank and with title "undefined". Need restart browser to refresh it.

**Comment by MatMoul** [comment]
@t7yang Thanks for your return.
For the blank page and undefined title, it's possible that is a bug.
I'll investigate...
