### ISSUE TITLE
Feature Request: search within speed dial bookmarks

### ISSUE THREAD

**Issue by Acid-Crash** [MatMoul/quickdial-webext#74]
If many bookmarks are present within Quick Dial search functionality can be quite helpful. 
Is it possible to add such feature (as an search-field above current bookmark grid)?

**Comment by MatMoul** [comment]
This is a good idea, but an hard work...
I've some priority before.

**Comment by benboeck** [comment]
Hello, thanks for your reply,
maybe it might work like this:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Extension_pages

**Comment by MatMoul** [comment]
I close this issue because I can't offer this feature...
In 20 years perhaps...
