### ISSUE TITLE
Selected icon is refreshed on firefox update

### ISSUE THREAD

**Issue by prakyg** [MatMoul/quickdial-webext#76]
After the Firefox received an update to 57.0.3, on the next restart, a large number of dials had custom preview icons missing and were defaulted to default screenshot of url.

Curiously this happened only to dials for which the custom preview icon was selected from a removable drive. 
The dials, whose icon was selected from the local drive instead (and although the icon doesn't exist on the drive itself), it stayed correct.

Note: My firefox also crashed when it prompted me to re-start.

**Comment by MatMoul** [comment]
#70 
#59 
I'm very limited but I'll try to find a more robust solution

**Comment by prakyg** [comment]
Are you trying to save the new settings every time firefox gets closed? Can you point me to the relevant code? I can take a look.

**Comment by MatMoul** [comment]
You can look on line 241 of the src/js/background.js file for the save method.
I use the api but ff save it as one big json file. This is the first problem.
Secondly, alway in background.js, I use the method app.GridNodes.sync.
This method sync all bookmarks with my storage. If a small change are made, Quick Dial save his settings.
