### ISSUE TITLE
How to move bookmark/folder from 2nd multipage to 1st multipage

### ISSUE THREAD

**Issue by Planet6** [MatMoul/quickdial-webext#77]
###############First : Great addon!
Question: How can I move a bookmark or folder from the 2nd multipage to 1st multipage ?
Changing the order in the bookmark menu won't change it and I can't drag it to the 1st multipage (top page).
Is this action (already?) possible and if not is it on the roadmap?
If it is possible; how?

PS] if this is the wrong place to ask; please direct me to the right place!

**Comment by MatMoul** [comment]
Look the next video @9:45
https://www.youtube.com/watch?v=zBmdZ4d4Yz4

**Comment by Planet6** [comment]
hehe I watched a big part of the video...but not till the end...

It's so easy: just open a 2nd firefox windows; windows 1 has the 1st multipage open and on windows 2 you scroll down to multipage 2 and drag the folder/bookmark to the wanted position on the other window

Thanks MatMoul!
