### ISSUE TITLE
Quick Dial Back Button Firefox doesn't work

### ISSUE THREAD

**Issue by yolinfl** [MatMoul/quickdial-webext#79]
Hi there,

I love your addon Quick Dial, but the Back Button Firefox doesn't work.
When I click on the arrow nothing happens.
What am I doing wrong, or what do I need to do?
Thank you.

**Comment by Hiromacu** [comment]
Hi, 

I think there is an add-on collision in your Firefox because everything is working here (Windows 10 64-bit, Firefox 58.0 64-bit). 

Both buttons, the back button on the navigation bar and the Quick Dial back button are working well to me.

**Comment by yolinfl** [comment]
The backbutton in FF is working correctly, but not the backbutton of the add-on, the big arrow to the left on the Dial screen. 
Is this a known issue? What can I do to make it work?
I have no other issues with my FF and am very clean with add-ons.

**Comment by MatMoul** [comment]
At this time no problem are know for the back button.
I use the next command when you click on it : window.history.back()
Try to open a console (F12) and look if you have an error.
