### ISSUE TITLE
Feature Request: Add option to use Bookmark's stored name for the tile

### ISSUE THREAD

**Issue by scienmind** [MatMoul/quickdial-webext#8]
Right now, the title of Quick Dial's thumbnails it set to be the page title as reported by the website itself.

Sometimes the title reported by the website may be sub-optimal, hence stored in bookmarks under user-defined name.

The request is to add a switch to enable user defined names to be used as items' titles in the Quick Dial  instead the self reported ones by websites.

**Comment by MatMoul** [comment]
I thouth about it and i'll work on it...

**Comment by MatMoul** [comment]
Now you can edit the title with the properties of the item.
But when you refresh the page, title is overwrited.
I'll add an option to preserve the title in future release

**Comment by MatMoul** [comment]
I've added a checkbox to lock the title in version 0.1.5
