### ISSUE TITLE
No real isssue, just an encouragement !

### ISSUE THREAD

**Issue by Planet6** [MatMoul/quickdial-webext#83]
I want to say that I really love your quickdial addon (now I know how too use it properly) Wish I would have replaced del Rio's Speed Dial (which turned shady without me noticing it) with quickdial years ago. 
I haven't seen you active in 2018.  Hope everything is ok and you can and will keep developing quickdial even further.
Ignore the haters on mozilla.org. The addon is great and has much potential. I've made a (IMHO) beautiful startpage (with subcategories) with transparent logos for my main pages/categories(folders) of bookmarks with your quickdial.
Nice! and thanks

Edit] I'm aware of the dials who have getting-logo-functions built-in, but those dials all use servers for their functionality and I hate that my browsing habits/personal data are the price too pay for a 'free' addon. So hopefully you will keep on going and I'll make sure too donate in future. Word.

Edit2] making an issue here was the only way I found to contact you. So there's that :D

**Comment by berlihingen** [comment]
I have to join the message above, including edits #1 and #2.
:)

**Comment by MatMoul** [comment]
Hello, I'm always here.
Just too many job.
I'll restart coding soon...

**Comment by benboeck** [comment]
Hello, one more thanks from me :)
Kind regards, Ben
