### ISSUE TITLE
More spacing between the dials

### ISSUE THREAD

**Issue by yolinfl** [MatMoul/quickdial-webext#84]
Hi there, I love the add-on, but I miss the option to change the spacing between my dials. I want as many as dials as possible on my screen, but I want a little bit more spacing between them. How can I do that?

**Comment by MatMoul** [comment]
In QuickDial settings, on Cells tab you can choose your margins.

**Comment by yolinfl** [comment]
That setting only makes my images smaller, and I would like to keep the same size. I only want more spacing between them.

**Comment by MatMoul** [comment]
If you have more space, the tiles should be smaller.
You can edit margins of the tile but you can try to work with the ratio of the grid and also with the stretch method of the tiles pictures. This parameters is available for the back and folder tiles in grid settings but you need to set this setting for each bookmarks.
