### ISSUE TITLE
Addon wipes/resets itself issue, Pre-57 user

### ISSUE THREAD

**Issue by AssCrab** [MatMoul/quickdial-webext#85]
Firefox 56.
As the title says, the addon has a tendency to completely wipe itself clean (i don't mean in the sense of deleting itself from the browser, but defaulting to its starting empty state) when Firefox itself crashes for whatever reason. Something that wouldn't be a problem with proper backup/data retention measures, whether automatic or manual backup option for users. 
The UI settings resetting i can deal with, but the loss of communication between QuickDial and the Quick Dial folder content? That's a pretty big drag.
Despite the Quick Dial bookmark folder being intact, QuickDial for some reason loses track of all the folder content and makes me re-do the whole bookmarking and folder making job via the dial page itself (it won't register when i directly make new folders and bookmarks into the folder that Quick Dial is supposed to communicate with) which is a nightmare and a waste of time.
I love this addon most of all as it has the best performance of the addons out there with a clean look and none of that effects bloat like FVD, as such i hope that there will be a minor final update for FF 56 users to only resolve this data retention issue since there's plenty of us staying with the old FF version.
Good luck to you and i hope you find the free time to polish this addon soon!

**Comment by MatMoul** [comment]
I know that when FF crash, the storage file can be corrupted.
This is a big problem that I want try to find a solution but I need some time.
Look at issue #59

**Comment by MatMoul** [comment]
I'm closing the issue because I've killed firefox when it save data and it seem that it's handled now...
