### ISSUE TITLE
"Capture in a new tab" wipes custom title

### ISSUE THREAD

**Issue by Jakob2014uafmx** [MatMoul/quickdial-webext#87]
If you use the "Capture in a new tab" feature in the right-click context menu of a tile, it removes the previous title of the tile (if you have manually set one) and uses a generated title instead.

**Comment by MatMoul** [comment]
Refresh and Capture in new tab update the title.
If you want to lock the title, you need to check the box on the right of the title in the tile setting

**Comment by Jakob2014uafmx** [comment]
Ok, thanks, didn't note that "lock" checkbox.
