### ISSUE TITLE
Option to select the bookmark folder 

### ISSUE THREAD

**Issue by BobBobovich** [MatMoul/quickdial-webext#88]
In the past I could make the "Other bookmarks" my default folder. The content of "Other bookmarks" would show up in the Fast Dial's first page. Now I can only make a new "Quick Dial" folder my default folder or give it a different name. I can't choose an existing bookmarks folder.

**Comment by eridanired** [comment]
Tried already typing `/Other Bookmarks` in the "Root folder" field of the QuickDial settings?

**Comment by BobBobovich** [comment]
Yes. It creates a folder named so in the "Bookmarks menu" folder. It doesn't take bookmarks from an original "Other bookmarks" folder.

**Comment by MatMoul** [comment]
To set your root folder, you have 2 solutions :
Start with / and provide all the path of your folder
Or start without / and provice the path from bookmark menu.
Normally, you can set anithing folders...

**Comment by vadimlitvinenko87** [comment]
it is not taking old bookmarks from folder
