### ISSUE TITLE
Allow scrolling and add scrolling bar

### ISSUE THREAD

**Issue by BobBobovich** [MatMoul/quickdial-webext#89]
The title explains it. Without scrolling and scrolling bar it is not convenient to move down the grid of bookmarks.

**Comment by MatMoul** [comment]
When I've time, I will work on #7
Alternatively you can use pageup/pagedown if you have difficulties with a pad or other

**Comment by MatMoul** [comment]
I'm closing this issue because it's duplicate with #7 with no return
