### ISSUE TITLE
Support Contextual Identities

### ISSUE THREAD

**Issue by scienmind** [MatMoul/quickdial-webext#9]
Mozilla have recently released [Contextual Identities](https://blog.mozilla.org/tanvi/2017/10/03/update-firefox-containers/)

However, seems that Quick Dial doesn't play well with it:
If a new tab is opened in any container other than default, the page is shown blank.

**Comment by scienmind** [comment]
Console output when opening new tab in a non-default container:
`TypeError: page is null[Learn More]                                 dial.js:11:1`

Seems like you are keeping `app.settings` in localStorage, which is separated per container.
Data in either Cookies, localStorage, indexedDB, or Cache is separated.
So when Quick dial opens in a non-default container, it has no settings.

Vital settings of Quick Dial, which has no potential of data leak across containers should be stored in other way.

More info: 
https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers
https://hacks.mozilla.org/2017/10/containers-for-add-on-developers/

**Comment by MatMoul** [comment]
Thanks for the return, I don't have tested this feature...
Now I return to the code...

**Comment by MatMoul** [comment]
Wow, following this page : https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers solutions are very limited...
Bookmark seem the only shared possibility...
Need reflection

**Comment by scienmind** [comment]
> ...solutions are very limited...
Bookmark seem the only shared possibility...

Seems like working in sync with Bookmarks will help with #4, #5 and here as well, as you won't have to store the grid itself. 

However, that'd be only half the solution, as you still need to keep the rest of the settings somewhere. 

The "Containers" separation is very similar to "Private Browsing". Case in point - opening **Quick Dial in Private Browsing mode doesn't work either** (same error), the basic extension settings are inaccessible.
(and private browsing is not related to FF57 at all, it's out there for a long long time now)

So basically, any extension that manages to preserve it's basic settings into the Private Browsing sessions figured out a way to do so (as, for example, ublock keeps the filter choices settings, maybe you can infer from such implementations).

Keep in mind though that reasonable data separation must be respected:
Meaning - while it's fine to store basic settings like grid size; colors, etc. (basically all the stuff user defines in the "settings" window) across sessions, Extra data, like thumbnails or cookies, obtained in a "Private" session should not be preserved.

---
That being said, I'm not the developer here, so it's of course up to you to decide on prioritization and design.
I'd just advice to consider that stuff like back-end data structures will be harder to refactor the further you go, so it may be useful to handle such limitations in the beginning and have a more robust base going forward :)

**Comment by MatMoul** [comment]
Private browsing mode is more problematic than identities and I need to work on...
I have found that : https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/incognito but it's not supported by firefox...
Now I found that : https://bugzilla.mozilla.org/show_bug.cgi?id=1329304
This can be a solution for private mode but not sure for identities

**Comment by scienmind** [comment]
Some similar extensions, for example Bookmark Dial (https://github.com/sblask/webextension-bookmark-dial) which seem to (somewhat) function in either probate mode or containers, looks like they store settings in `browser.storage.local`.

Now, I didn't look too close on it, and if it indeed does the things correctly, but maybe you'll find it useful.

**Comment by MatMoul** [comment]
@scienmind Thanks, I think I know what to do but it remains to do so ...

**Comment by MatMoul** [comment]
Version 0.1.0 published Contextual Identities support

**Comment by scienmind** [comment]
Looks like working via `messages` did the trick

@MatMoul : Is there a reason to suspect that any site data/cookies/db/cache will be acquired by Quick Dial in Private Mode/Contiainer and then retained back to Normal Mode/another Container?

**Comment by MatMoul** [comment]
@scienmind I didn't quite understand your question

**Comment by scienmind** [comment]
For example:

1. I open private browsing, go to site A, it stores cookies and cache
2. Go to site B, it stores cookies and cache, and so on. 
3. Then i open Quick Dial and it generates thumbnails and such. 

So the question is: 
Is any data produced by Quick Dial in step 3 is influenced by steps 1 or 2 (like login data, etc.) ??
 - If yes, than will it still be present once Quick Dial opened in Non-Private (aka normal) browsing mode?
Like, thumbnails generated while logged in to the website (displaying logged-in view of the website) in private browsing are still visible after private browsing session was terminated?

**Comment by MatMoul** [comment]
The iframe method always use the default context for cookie and session. So the refresh command make a thumbnails with the default context.
The second method Capture in a new tab use the current context and send the captured image.
The captured image is shared on all context.

**Comment by scienmind** [comment]
Thanks for the info!

Btw. it might be good to document it somewhere (readme of a sort)
