### ISSUE TITLE
Move a bookmark between pages

### ISSUE THREAD

**Issue by mahmutelmas06** [MatMoul/quickdial-webext#95]
İ cannot drag and drop a bookmark among pages.

**Comment by MatMoul** [comment]
Not sur what the question?
Look the video...
You can open two Firefox window and drag page to an other page...
But dragging to an other folder is not supported now.

**Comment by mahmutelmas06** [comment]
I mean if there is more than 1 pages on quickdial i cannot move from page 2 to page 1 by dragging it. I have to delete the bookmark from quickdial page 2 and create new bookmark on page 1 to order it.

**Comment by MatMoul** [comment]
https://www.youtube.com/watch?v=zBmdZ4d4Yz4 @9:42
Open two Window side by side and drag...
