### ISSUE TITLE
if dial is a background image it is displayed as text/code preview image

### ISSUE THREAD

**Issue by derdershat** [MatMoul/quickdial-webext#96]
Hi MatMoul,

I separate issue as suggested...

I used Fast Dial with some blanks/spacers (link to a background image) to seperate the dials/ to make categories on my main page. [like this](https://imgur.com/bcmTBFV) (picture is from Firefox 52 ESR with Fast Dial) 
but with Quick Dial the background image is displayed as code [like this](https://imgur.com/xrMrzjn)

to reproduce this please add this url to a dial 
http://www.userlogos.org/files/backgrounds/trogdor/mybackground.jpg

I get as preview text and not a gray image

**Comment by MatMoul** [comment]
Try to use capture as new tab or upload the image...
